config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "controllers/omniauth_callbacks" }


  root 'static_pages#home'

  resources :users do
	resources :reviews
        resources :diaries
  end
   
  resources :account_activations, only: [:edit]
  resources :posts,               only: [:create, :destroy]

  get "/users/search/", to: 'users#search'

  get    'info'      => 'static_pages#info'
  get    'aboutus'   => 'static_pages#aboutus'
  get    'contactus' => 'static_pages#contactus'
  get    'valuta'    => 'static_pages#valuta'


  get "*path", to: 'application#catch_404', via: :all
  post "*path", to: 'application#catch_404', via: :all



end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true

  validates :content, presence: true, length: {maximum: 1000}


end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController


    def index
    end

    def new
    end

    def show
        @diary = User.find(params[:user_id]).diary
        @user = User.find(params[:user_id])
    end


    def create
        @user = current_user
        @diary = current_user.build_diary(params.require(:diary).permit(:content))
        if @diary.save
            flash[:success] = "Diario creato"
            redirect_to user_diary_path(@user,@user.diary)
        else
            flash[:danger] = "ATTENZIONE! Non è stato possibile creare un diario vuoto"
            redirect_to user_path(current_user)
            return
        end
    end

    def edit
        @diary = User.find(params[:user_id]).diary
        @user = User.find(params[:user_id])

    end

    def update
        if !current_user.diary.blank?
            if @diary = current_user.diary.update(params.require(:diary).permit(:content))
               redirect_to user_diary_path(current_user,current_user.diary), notice: 'Diario aggiornato'
            else
               render :edit
            end
        else
            redirect_to user_path(current_user)
        end
    end

    def destroy
       if !current_user.diary.blank?
           current_user.diary.destroy
           flash[:success] = "Diario eliminato"
           redirect_to user_diary_path(current_user,current_user.diary)
       else
           redirect_to user_diary_path(current_user,current_user.diary), notice: 'Non esiste nessun diario ancora!'
       end

    end
end

app/views/diaries/_diary.html.erb
<span class="content">
    <%= diary.content %>
</span>

app/views/diaries/edit.html.erb
<% provide(:title, "Diary") %>


<h1>Modifica il tuo diario</h1>


<%= form_for :diary, url: user_diary_path(current_user), html: { method: :put, params: current_user.diary } do |d| %>

      <div class="field">
         <%= d.text_area :content, cols: 20, rows: 15%>
      </div>
      <%= d.submit "Aggiorna", class: "btn btn-primary" %>

<% end %>

<br>
<br>
<br>

<%= link_to 'Indietro', user_diary_path(current_user), class: "btn btn-primary" %>

app/views/diaries/index.html.erb
<% provide(:title, "Diary") %>

<h1>Il mio diario</h1>



<%= link_to 'Crea', '#'  %> |
<%= link_to 'Modifica', '#'  %> |
<%= link_to 'Elimina', '#'  %> |

app/views/diaries/new.html.erb
<% provide(:title, "Diary") %>

<% flash.each do |type, msg| %>
    <div class = "alert alert-info">
       <%= msg %>
    </div>
<% end %>

<h1>Crea il tuo diario</h1>


<%= form_for :diary, url: user_diaries_path(current_user), html: { method: :post } do |d| %>
      <div class="field">
         <%= d.text_area :content, cols: 20, rows: 15, placeholder: "Annota qui", id: :write_diary%>
      </div>
      <%= d.submit "Crea", class: "btn btn-primary" %>

<% end %>

<br>
<br>
<br>

<%= link_to 'Indietro', user_path(current_user), class: "btn btn-primary" %>

app/views/diaries/show.html.erb
<% provide(:title, "Diary") %>

<% flash.each do |type, msg| %>
    <div class = "alert alert-info">
       <%= msg %>
    </div>
<% end %>


<h1>Il mio diario</h1>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
        <strong><%= @user.name %></strong> |
        <strong><%= @user.desease %></strong> 
    </section>
  </aside>
</div>

<% if @user.diary.nil? %>
   <h3> Diario non creato! </h3>
<% else %>
   <div class="col-md-4">
      <% if current_user?(@user) %>
         <h3>Il tuo diario</h3>
         <%= render current_user.diary %>
      <% else %>
         <h3>Diario di <%= @user.name %></h3>
	 <%= render @user.diary %>
      <% end %>
  </div>
<% end %>

<br>
<br>
<br>
<br>
<br>
<br>

<% if current_user?(@user) %>
    <h3>Le tue recensioni </h3>
    <% if current_user.reviews.empty?  %>
        <p> Ancora non hai recensioni! </p>
    <% end %>
<% else %>
    <h3> Le recensioni di <%= @user.name %></h3>
    <% if @user.reviews.empty?  %>
    	<p> <%= @user.name %> non ha ancora recensioni! </p>
    <% end %>
<% end %>



<% @user.reviews.each do |review| %>
	<p>
	    <bf><h5>Recensione: </h5>
	    <bf></bf><%= review.body %> <br>
            <br>
            <bf>Voto: </bf><%= review.score %> <br>
  	</p>
        
        <p>
	<%= link_to 'Rimuovi recensione', [review.user, review],
		   method: :delete,
		   data: { confirm: "Sei sicuro di voler eliminare la recensione?" } %></p>

<% end %>


<br>
<br>
<br>
<br>
<br>
<br>

<% if current_user?(@user) %>
      <% if !@user.diary.nil? %>
	<%= link_to 'Modifica diario', edit_user_diary_path(current_user,current_user.diary), class: "btn btn-primary"   %> |
	<%= link_to 'Cancella diario', user_diary_path(current_user), method: :delete,
		   data: { confirm: "Sei sicuro di voler eliminare il diario?" }, class: 'btn btn-danger'  %>
      <% else %>
        <%= link_to 'Crea diario', new_user_diary_path(current_user,current_user.diary), class: "btn btn-primary" %>
      <% end %>
<% else %>
	<%= link_to 'Fai una recensione', new_user_review_path(current_user,current_user.reviews), class: "btn btn-primary" %>
<% end %>