config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "controllers/omniauth_callbacks" }


  root 'static_pages#home'

  resources :users do
	resources :reviews
        resources :diaries
  end
   
  resources :account_activations, only: [:edit]
  resources :posts,               only: [:create, :destroy]

  get "/users/search/", to: 'users#search'

  get    'info'      => 'static_pages#info'
  get    'aboutus'   => 'static_pages#aboutus'
  get    'contactus' => 'static_pages#contactus'
  get    'valuta'    => 'static_pages#valuta'


  get "*path", to: 'application#catch_404', via: :all
  post "*path", to: 'application#catch_404', via: :all



end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :posts, dependent: :destroy

    has_one :diary, dependent: :destroy

    has_many :reviews, dependent: :destroy

    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

    mount_uploader :picture, PictureUploader

    validate :picture_size

    validates :name, presence: true, length: { maximum: 50 }
    validates :surname, presence: true, length: { maximum: 50 }
    validates :city, presence: true, length: { maximum: 50 }
    validates :desease, presence: true, length: {maximum: 50}
    validates :province, length: { maximum: 2 }
    #validates :birth, allow_blank: true, format: { with: /\A(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[13-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2}) \z/ }
    #validates :birth, format: { with: /\A(?:(?:(?:0[13578]|1[02])(\/)31)\1|(?:(?:0[1,3-9]|1[0-2])(\/)(?:29|30)\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:02(\/)29\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:(?:0?[1-9])|(?:1[0-2]))(\/)(?:0[1-9]|1\d|2[0-8])\4(?:(?:1[6-9]|[2-9]\d)?\d{2})\z/ }
    #validates :birty, format: { with:  /\A(3[01]|[12][0-9]|0?[1-9])/(1[0-2]|0?[1-9])/(?:[0-9] {2})?[0-9]{2}\z/ }


    def feed
        Post.where("user_id = ?", id)
    end

    def feed_admin
        post_ids =  "SELECT id FROM users"
        Post.where("user_id IN (#{post_ids})")
    end

    def feed_users
        post_ids =  "SELECT id FROM users"
        Post.where("user_id IN (#{post_ids})")
    end

    def self.search(search)
        key = "%#{search}%"
        if search
            where('name LIKE ? OR desease LIKE ?', key, key)
        else
            all
        end
    end

    def averageScore
        total = 0
        self.reviews.each do |r|
            total += r.score
        end

        return (total.to_f/self.reviews.count.to_f).round(2)
    end



    def User.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.email = auth.info.email
          user.password = Devise.friendly_token[0,20]
          user.name = auth.info.first_name
          user.surname = auth.info.last_name
          user.data = auth.info.birthday
          user.city = auth.info.city
          user.desease = auth.info.desease
          user.save

        end
    end

    def User.new_with_session(params, session)
        super.tap do |user|
          if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
            user.email = data["email"] if user.email.blank?
          end
        end
    end



    private

         # Convalida la dimensione di un'immagine caricata.
        def picture_size
            if picture.size > 5.megabytes
                errors.add(:picture, "Dovrebbe essere inferiore a 5 MB")
            end
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :current_user, only: [:show, :edit, :update, :destroy]


  def index
    @user = current_user
    @users = User.search(params[:search])
  end


  def show
   id = params[:id]
    if id.nil? then
      redirect_to root_path
      return
    end
    @user = User.find(id)
    @posts = @user.posts.paginate(page: params[:page])
    @diary = @user.diary
    @reviews = @user.reviews if !@user.reviews.empty?
  end


  def new
    @user = User.new
  end


  def edit
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to user_path(current_user)
        #@user.send_activation_email
        #flash[:info] = "Per favore verifica la tua email per attivare il tuo account"
        #redirect_to root_url
      else
        flash[:danger] = "Utente non salvato"
        render :new
    end
  end


  def update
    @user = current_user
      if @user.update_attributes(params.require(:user).permit(:name, :surname, :email, :city, :province, :street, :birth, :desease, :picture))
        redirect_to user_path(@user), notice: 'Profilo aggiornato'
      else
        render :edit
      end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to root_path, notice: 'Utente eliminato'
    return
  end



  private
    # Utilizza i callback per condividere l'impostazione o i vincoli comuni tra le azioni.
    def set_user
      @user = User.find(params[:id])
    end

    # Consenti solo un elenco di parametri attendibili.
    def user_params
      params.require(:user).permit(:name, :surname, :email, :city, :province, :street, :birth, :desease, :password, :picture)
    end


    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    # Conferma un utente amministratore
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :province %>
    <%= form.text_field :province %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :birth %>
    <%= form.date_select :birth %>
  </div>

  <div class="field">
    <%= form.label :desease %>
    <%= form.text_field :desease %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<h1>Modifica il tuo profilo</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(resource, as: current_user, url: user_path(resource_name), html: { method: :put, params: current_user}) do |f| %>
      <%= render "devise/shared/error_messages", resource: resource %>


      <%= f.label :nome %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :cognome %>
      <%= f.text_field :surname, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :città %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :provincia %>
      <%= f.text_field :province, class: 'form-control' %>

      <%= f.label :via %>
      <%= f.text_field :street, class: 'form-control' %>

      <%= f.label :compleanno %>
      <%= f.date_select :birth, min: Date.new(1900, 01, 01), max: Date.today, class: 'form-control' %>

      <%= f.label :malattia %>
      <%= f.text_field :desease, class: 'form-control' %>

      <%= f.label :foto %>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>

      <%= f.submit "Salva", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'Indietro', current_user, class: "btn btn-primary" %>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('La dimensione massima del file è 5 MB. Scegli un file più piccolo.');
    }
  });
</script>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<div class="center jumbotron">
	<h4>I tuoi risultati:</h4>

	<ul class="users">
	  <% @users.each do |user| %>
	    <li>
	      <strong><%= link_to user.name, user %></strong>
	      <%= image_tag user.picture.url if user.picture? %>
	      <% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "Cancella utente", user, method: :delete,
		                          data: { confirm: "Sei sicuro di voler eliminare definitivamente l'utente corrente?" } %>
	      <% end %>
	    </li>
	  <% end %>
	</ul>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Registrati') %>

    <% flash.each do |type, msg| %>
      <div class = "alert alert-info">
        <%= msg %>
      </div>
    <% end %>

<h1>Registrazione utente</h1>

<script>
  $( document ).ready(function() {
    $('.datepicker').datepicker({
      inputFormat: ["dd/MM/yyyy"],
      outputFormat: 'dd/MM/yyyy',
     });
  });

</script>

<div class="row">
<div class="col-md-6 col-md-offset-3">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= render "devise/shared/error_messages", resource: resource %>

      <%= f.label :Nome %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :Cognome %>
      <%= f.text_field :surname, class: 'form-control' %>

      <%= f.label :Email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :Città %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :Provincia %>
      <%= f.text_field :province, class: 'form-control' %>

      <%= f.label :Via %>
      <%= f.text_field :street, class: 'form-control' %>

      <%= f.label :Nascita%>
      <%= f.date_field :birth, id: "datepicker", min: Date.new(1900, 01, 01), max: Date.today, class: 'form-control'%>
      

      <%= f.label :Malattia %>
      <%= f.text_field :desease, class: 'form-control' %>

      <%= f.label :Password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Conferma password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crea il mio account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<h3>Ricerca utenti</h3>
<ul class="users">
  <%= render @users %>
</ul>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h4>Profilo</h4>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">

      <h1>
	  <%= image_tag @user.picture.url if @user.picture? %>
	  <br>
          <br>
          <strong>Nome:</strong>
          <%= @user.name %>
          <br>
          <strong>Cognome:</strong>
          <%= @user.surname %>
          <br>
          <strong>Email:</strong>
          <%= @user.email %>
          <br>
          <strong>Città:</strong>
          <%= @user.city %>
          <br>
          <strong>Provincia:</strong>
          <%= @user.province %>
          <br>
          <strong>Via:</strong>
          <%= @user.street %>
          <br>
          <strong>Data di nascita:</strong>
          <%= @user.birth %>
          <br>
          <strong>Malattia:</strong>
          <%= @user.desease %>
          <br>

      </h1>
    </section>
           <br>
           <br>
	   <% if @user == current_user %>
		<%= link_to 'Modifica', edit_user_path(current_user), class: "btn btn-primary"  %> |
		<%= link_to 'Modifica password', edit_user_password_path(current_user), class: "btn btn-primary"  %> |
		<%= link_to 'Diario', user_diary_path(current_user), class: "btn btn-primary" %>
		<% if !current_user.admin? %>
		  | <%= link_to 'Cancella account', user_path(current_user), method: :delete, data: { confirm: 'Sei sicuro di voler cancellare il tuo account?' }, class: 'btn btn-danger' %>
		<% end %>
	<% else %> 
		 <%= link_to 'Diario', user_diary_path(@user), class: "btn btn-primary" %>
	<% end %>
  </aside>



  <div class="col-md-4">
    <% if !current_user.admin? %>
      <% if @user.posts.any? %>
        <h3>I tuoi post (<%= @user.posts.count %>)</h3>
        <ol class="posts">
          <%= render @posts %>
        </ol>
        <%= will_paginate @posts %>
      <% end %>
    <% end %>
  </div>
</div>