config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "controllers/omniauth_callbacks" }


  root 'static_pages#home'

  resources :users do
	resources :reviews
        resources :diaries
  end
   
  resources :account_activations, only: [:edit]
  resources :posts,               only: [:create, :destroy]

  get "/users/search/", to: 'users#search'

  get    'info'      => 'static_pages#info'
  get    'aboutus'   => 'static_pages#aboutus'
  get    'contactus' => 'static_pages#contactus'
  get    'valuta'    => 'static_pages#valuta'


  get "*path", to: 'application#catch_404', via: :all
  post "*path", to: 'application#catch_404', via: :all



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
  end

  def new
    @review = Review.new
    #@user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])

    @review = @user.reviews.build(params.require(:review).permit(:body, :score, :user))
    if @review.save
        flash[:success] = "Recensione pubblicata"
        redirect_to user_diary_path(@user,@user.diary)
    else
        flash[:danger] = "Recensione non pubblicata"
        redirect_to root_path
    end
  end


  def edit
    @review = User.find(params[:user_id]).reviews.find(params[:id])
  end

  def show
    @review = User.find(params[:user_id]).reviews.find(params[:id]).paginate(page: params[:page])
    @user = User.find(params[:user_id])
  end

  def update
    @review = User.find(params[:user_id]).reviews.find(params[:id])

    if @review.update(review_params)
      redirect_to @review.user
    else
      render :edit
    end

  end


  def destroy
    #@user = User.find(params[:user_id])
    @review = current_user.reviews.find(params[:id])
    @review.destroy
    redirect_to user_diary_path(current_user,current_user.diary)

  end


   private

    def review_params
      p = params.require(:review).permit(:body, :score, :user)
      #{:body=> p[:body], :score=>p[:score], :user=>User.find(p[:user])}
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/create.html.erb
<h2> Fai una recensione </h2>

<%= form_with model: [ @review.user, @review ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :score %><br>
    <%= form.collection_select :score, [1,2,3,4,5,6,7,8,9,10], :to_i, :to_s%>
  </p>

  <p>
    <%= form.label :user %><br>
    <%= form.collection_select :user, User.all, :id, :name%>
  </p>

  <p>

    <%= form.submit "Pubblica recensione" %>
  </p>
<% end %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h2> Modifica una recensione </h2>

<%= form_with model: [ @review.user, @review ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, class 'form-control' %>
  </p>
  <p>
    <%= form.label :score %><br>
    <%= form.collection_select :score, [1,2,3,4,5,6,7,8,9,10], :to_i, :to_s%>
  </p>

  <p>
    <%= form.label :user %><br>
    <%= form.collection_select :user, User.all, :id, :name%>
  </p>

  <p>
  	
    <%= form.submit "Modifica recensione" %>
  </p>
<% end %>

app/views/reviews/new.html.erb
<% provide(:title, "Review") %>

<h1> Scrivi una recensione </h1>

<%= form_for :review,  url: user_reviews_path(current_user), html: { method: :post } do |form| %>
  <p>
    <%= form.label :recensione %><br>
    <%= form.text_area :body,cols: 20, rows: 15, class: 'form-control' %>
  </p>
  <p>
    <%= form.label :voto %><br>
    <%= form.collection_select :score, [1,2,3,4,5,6,7,8,9,10], :to_i, :to_s%>
  </p>

  <p>
    <%= form.submit "Pubblica recensione", class: "btn btn-primary"  %>
  </p>
<% end %>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>