config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "controllers/omniauth_callbacks" }


  root 'static_pages#home'

  resources :users do
	resources :reviews
        resources :diaries
  end
   
  resources :account_activations, only: [:edit]
  resources :posts,               only: [:create, :destroy]

  get "/users/search/", to: 'users#search'

  get    'info'      => 'static_pages#info'
  get    'aboutus'   => 'static_pages#aboutus'
  get    'contactus' => 'static_pages#contactus'
  get    'valuta'    => 'static_pages#valuta'


  get "*path", to: 'application#catch_404', via: :all
  post "*path", to: 'application#catch_404', via: :all



end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small> CoViD application</small>
  <nav>
    <ul>
      <li><%= link_to "Info", info_path %></li>
      <li><%= link_to "About us", aboutus_path  %></li>
      <li><%= link_to "Contact us", contactus_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Valuta", '#' %></li>
        <% if current_user.admin? %>
	  <li><%= link_to "Utenti", users_path %></li>
        <% end %>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container"> 
    <%= link_to "CoViD", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Profilo", user_path(current_user) %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>CoViD</title>

    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
         <%= yield %>
         <%= render 'layouts/footer' %>
    </div>
  </body>
</html>